PMPHAlEVIKJ]KBwLE@KSWlEVIKJMfE]EJCEJ.@AWGVMTPMKJmJESKVH@KBWLE@KSWESEVVMKVBMJ@WLEVIKJ]EIM@WPGLEKW
mJWTMVA@F]oVMWPEHWWP]HAPLMWPVEGOGETPQVAWPLAAWWAJGAKBWPVQCCHAEJ@PVMQITL
.TVKITPaJAVCAPMGVKGOSMPLIAHK@MGCQMPEVVMBBW@VMRMJC@VQIFAEPWEJ@EFHAJ@KBPVE@MPMKJEHEJ@IK@AVJVKGOAHAIAJPW
hE]AVA@LEVIKJMAW@AATFEWWCVKKRAWMJPAJWAIEHARKGEHSMPLEGKIIEJ@MJCTVAWAJGA
.GKRAVeVPtVKITPeI]WPMGEHSEVVMKVWPEJ@MJCKJEVKGO]GHMBBQJ@AVEWPKVI]WO]HMCLPJMJCMHHQIMJEPMJCPLAWGAJA
eFHAJ@KBIK@AVJEJ@EJGMAJPWP]HAWSMPLE@VEIEPMGEJ@ATMGBAAH
fKH@GKHKVWEJ@WPVMOMJCGKJPVEWPW
.WB\PLQJ@AVWPVMOAWAGLKMJCBKKPWPATWWSKV@QJWLAEPLMJC@MWPEJPFEPPHAGVMAW.RKGEHWIEHARKGEHTKSAVBQHVKGOWP]HA@]JEIMGVEJCAAIKPMKJEHMJPAJWMP].RKGEHWwPVQGPQVA@VKGOPVEGOSMPLWPVKJCMJPVKEJ@MITEGPBQHKQPVKMJGHQ@MJCTKSAVBQH@VKTWSMPLMJPAJWAIEHARKGEH.OA]SKV@WVKGOIAPEHEHPAVJEPMRALEV@VKGOCQMPEV@VQIWTKSAVBQHATMGWKQJ@PVEGOGMJAIEPMGoVMWPEHMJPAJWA@]JEIMGFEPPHA.GK@AjEIA}EIE@EiKJKCEPEVMpLA`AIKJlQJPAV.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]oVMWPEH	tEWPMwAITQVJE
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV}.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGWMJPVKPLQJ@AVy..VMBBFQMH@	QTy..RAVWA∆§∑wLE@KS∆§ΩWgEHHy.mJPLA@EVOSLAVAAGLKAW@SAHH.eSEVVMKVWLAEVPFACMJWPKWSAHH.KKKKKKMMMMMM..gLKVQW∆§∑wPKVI∆§ΩWaIFVEGAy.hMCLPJMJCGVEGOWPLAWLE@KSW@EJGA.mJLEVIKJ]SAPEOAKQVWPEJGA.SKKKKK.MMMMMMMM..fVM@CA∆§∑sEVVMKV∆§ΩWtEPLy.pLVKQCLPLAWPKVISASEHOEHKJA.wPVAJCPLEJ@GKQVECASALERACVKSJ.eLLLLWLLLLLLL..RAVWAy.pLAJMCLPMWHKJCFQPSAWPEJ@PEHH.mJPLAAJ@SAHHGKJUQAVEHH.^^^^^^LLLLLL..KQPVK	bE@AMJPKhMCLPy..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
